services:
  camkeep:
    image: r0n9/camkeep:latest
    container_name: camkeep
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/app/config
      - ./records:/app/records
    ports:
      - "9110:9110"      # CamKeep Web 控制台
      - "1984:1984"      # go2rtc API 端口
      - "8554:8554"      # RTSP 服务端口
      - "8555:8555/tcp"  # WebRTC 端口 (必须暴露，否则无画面)
      - "8555:8555/udp"