version: "3.8"

services:
  camkeep:
    image: ghcr.io/r0n9/camkeep:latest
    container_name: camkeep
    restart: unless-stopped
    network_mode: "host"
    shm_size: "512m"
    environment:
      - TZ=Asia/Shanghai
      - CAMKEEP_AUTH_PASSWORD=admin
    volumes:
      - "${wizard_config_dir:-/vol1/1000/camkeep/config}:/app/config"
      - "${wizard_records_dir:-/vol1/1000/camkeep/records}:/app/records"
